---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart prometheus
  ansible.builtin.service:
    name: prometheus
    state: restarted

- name: Restart node_exporter
  ansible.builtin.service:
    name: node_exporter
    state: restarted

- name: Restart nginx_exporter
  ansible.builtin.service:
    name: nginx_exporter
    state: restarted

- name: Restart grafana
  ansible.builtin.service:
    name: grafana-server
    state: restarted
