---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: common-test
    image: geerlingguy/docker-debian12-ansible
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
provisioner:
  name: ansible
  inventory:
    host_vars:
      common-test:
        vault_deploy_ssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAItest test@molecule"
verifier:
  name: ansible
